version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=your_username
      - DB_PASS=your_password
      - DB_NAME=your_dbname

  db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_dbname
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
